### PR TITLE
Add purple background to newsletter

### PR DESCRIPTION
**Pull request by Quentin-Bernigaud**
Add some style to the newsletter section

### CODE REVIEW

**Comment by Quentinchampenois** [comment]
Hi @Quentin-Bernigaud, thank you for your work ! 
Could you please add a description in your PR, eventually add screenshots if the PR change the UI before code review ?

**Review by Quentinchampenois — APPROVED** [review]

**Review by Quentinchampenois — APPROVED** [review]
Great work, seems good to me !

**Review by moustachu — APPROVED** [review]
Indeed ! Screenshots "before / after" would have been nice ! 

Good job

**Review by MoretS — APPROVED** [review]

**Comment by armandfardeau** [comment]
Hi @Quentin-Bernigaud, seems good to me. Add some screenshots next time, please 🙏

**Review by armandfardeau — APPROVED** [review]

**Comment by virgile-dev** [comment]
> Indeed ! Screenshots "before / after" would have been nice !
> 
> Good job

+1 

@Quentin-Bernigaud I'm curious to know if the header and footer of the emails background color are just a simple variable to change. It seems you did more than that here.

**Pull request merged**
